[profile.default]
optimizer = true
optimizer_runs = 99999
evm_version = 'istanbul'
ffi = true
ast = true
via_ir = true
build_info = true
extra_output = ["storageLayout"]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache_forge'

remappings = [
    "@openzeppelin/contract/=lib/openzeppelin-contracts",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/contracts/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@solmate/=lib/solmate",
]
