[default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

[profile.default]
optimizer = true
optimizer_runs = 200
evm_version = 'cancun'

remmaings=["@openzeppelin/contract/=lib/openzeppelin-contracts", "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable"]