[profile.default]
optimizer = true
optimizer_runs = 200
evm_version = 'cancun'
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

remmaings=["@openzeppelin/contract/=lib/openzeppelin-contracts", "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable", "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/contracts"]