[profile.default]
optimizer = true
optimizer_runs = 200
evm_version = 'cancun'
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache_forge'
# solc_version = "0.8.26"          # Default version for your contracts

# [profile.default.overrides]
# "lib/v3-periphery" = { version = "0.7.6" } # Uniswap V3 periphery uses Solidity 0.7.6
# "lib/v3-core" = { version = "0.7.6" }

remappings = [
    "@openzeppelin/contract/=lib/openzeppelin-contracts",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/contracts/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@solmate/=lib/solmate",
]
